version: "2"
services:
  sonarqube:
    image: sonarqube:6.4
    expose:
      - 9000
    ports:
      - "192.168.20.1:9000:9000"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=qweqweasdasd123123
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  db:
    image: postgres:latest
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=qweqweasdasd123123
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

  gitlab:
    image: gitlab/gitlab-ce:latest
    expose:
      - 22
      - 80
      - 443
    ports:
      - "192.168.20.1:22:22"
      - "192.168.20.1:80:80"
      - "192.168.20.1:443:443"
    volumes:
      - /srv/gitlab/logs:/var/log/gitlab
      - /srv/gitlab/data:/var/opt/gitlab
      - /srv/gitlab/config:/etc/gitlab

  gitlab-runner:
    image: docker:17.06.0-ce-dind
    command: --storage-driver=overlay2
    networks:
      - sonarnet
    privileged: true
    restart: always
    volumes:
      - /var/lib/docker

networks:
  sonarnet:
    driver: bridge

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:
    